### ISSUE TITLE
Description of managed compute environment scheduling

### ISSUE THREAD

**Issue by bertrand-caron** [awsdocs/aws-batch-user-guide#10]
Hi,

In the `Compute Environment`, there is a very high-level description of the managed compute environments, but absolutely no description of the nitty-gritty of how the scheduling of instance is done, and how often is it refreshed. Specifically, there is no mention of the 10 minute delay that many people are reporting[[1]](https://forums.aws.amazon.com/thread.jspa?threadID=245225). Shedding some light of these mechanism would be much appreciated by developers using AWS Batch.
Thanks

**Comment by HLeeHart** [comment]
The 10 minute issue is gone. The release of the fair share scheduling feature should clear up a lot of issues around the old FIFO scheduler.
