### ISSUE TITLE
"sudo stop ecs"?

### ISSUE THREAD

**Issue by entonos** [awsdocs/aws-batch-user-guide#11]
on step 4 of https://github.com/awsdocs/aws-batch-user-guide/blob/master/doc_source/create-batch-ami.md

`sudo stop ecs`

should that be

`sudo systemctl stop ecs`?

**Comment by HLeeHart** [comment]
Thank you for raising this issue. The command needed differs for Amazon Linux and Amazon Linux 2. I have updated the docs to reflect this.
