### ISSUE TITLE
Incorrect Docker File in https://docs.aws.amazon.com/batch/latest/userguide/array_index_example.html

### ISSUE THREAD

**Issue by smrutiranjantripathy** [awsdocs/aws-batch-user-guide#12]
Hi Team ,
When we execute docker file explained in the example  for print-color
https://github.com/awsdocs/aws-batch-user-guide/blob/master/doc_source/array_index_example.md

**It throws the error:**
/bin/sh: /tmp/print-color.sh: Permission denied
/bin/sh: /tmp/print-color.sh: Permission denied

This issue is appearing because of missing executable  permissions for 
print-color.sh in Docker file 

`FROM busybox
COPY print-color.sh /tmp/print-color.sh
COPY colors.txt /tmp/colors.txt
ENTRYPOINT /tmp/print-color.sh`

We need to add permissions by adding one line 
`RUN chmod +x /tmp/print-color.sh  in the Dockerfile`

**Comment by HLeeHart** [comment]
Fix was merged. Closing
