### ISSUE TITLE
Cloudwatch metrics for AWS Batch jobs

### ISSUE THREAD

**Issue by oscarbc96** [awsdocs/aws-batch-user-guide#14]
Hi team!

In our team, we monitor our services using cloudwatch metrics. AWS doesn't provide cloudwatch metrics for AWS Batch jobs (list of supported cloud watch metrics https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/aws-services-cloudwatch-metrics.html).
So our idea is to implement a lambda that gets triggered by job status change events and create custom metrics based on the event data. 

We were thinking to have these metrics and dimensions:

**Proposed AWS Batch Job CloudWatch Metrics**

Metric | Description
-- | --
Duration | Measures the elapsed wall clock time from when the function code starts executing as a result of an invocation to when it stops executing. The maximum data point value possible is the function timeout configuration. Units: Milliseconds (max)
Errors | Measures the number of invocations that failed due to errors in the function. Failed invocations may trigger a retry attempt that succeeds. Units: Count (sum)
Invocations | Measures the number of times a function is invoked in response to an event. This includes successful and failed invocations, but does not include throttled attempts.Units: Count (sum)

**Proposed AWS Batch Job Dimensions**

Dimension | Description
-- | --
Definition | Filters the metric data by AWS batch job definition
Name | The name of the job.
Id | The ID for the job.
ExecutedVersion | Extract job version from JobDefiniton?

We would like to know your opinion and if this is going to be implemented soon.
Cheers,
Oscar

**Comment by ignaciobolonio** [comment]
I am also interested on this

**Comment by magantisurya** [comment]
I am working on AWS batch and i have done coding in Java and can able to run when i deploy it manually. But its very hard to automate and read environment variables and also pass parameters so that we can externalize AWS secrets ....

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
