### ISSUE TITLE
Sorting by any column on dashboard is drunk

### ISSUE THREAD

**Issue by nlothian** [awsdocs/aws-batch-user-guide#17]
This is supposed to sort by the number of runnable job. It does _something_, but I don't understand what. 

If those arrows aren't supposed to represent sorting perhaps the user guide could explain what they are. 

![image](https://user-images.githubusercontent.com/117304/97834982-059d6d80-1d29-11eb-9067-562a654e512e.png)
![image](https://user-images.githubusercontent.com/117304/97834989-0afab800-1d29-11eb-9c69-a690f0e39d3c.png)

**Comment by HLeeHart** [comment]
The issue appears to have been fixed.
