### ISSUE TITLE
"Propagate tags" section of doc_source/job_definition_parameters.md has incorrect key name

### ISSUE THREAD

**Issue by fred-vogt-dod** [awsdocs/aws-batch-user-guide#19]
I can submit a PR if needed.

## Details
`platformCapabilities` should be `propagateTags`:
* https://github.com/awsdocs/aws-batch-user-guide/blob/master/doc_source/job_definition_parameters.md
* Live site:
  * ![Screen Shot 2020-12-06 at 3 32 45 PM](https://user-images.githubusercontent.com/70547635/101296598-1d10c000-37d9-11eb-9fd6-1c31769f43ae.png)
  * ![Screen Shot 2020-12-06 at 3 35 36 PM](https://user-images.githubusercontent.com/70547635/101296609-2dc13600-37d9-11eb-9a4e-e9852ce14b5e.png)

**Comment by HLeeHart** [comment]
Fixed with commit a2bee0dab1a127321b4363a3b133492774a1bb93. Thanks for raising this issue!
