### ISSUE TITLE
Any examples in Java

### ISSUE THREAD

**Issue by magantisurya** [awsdocs/aws-batch-user-guide#21]
I am finding it hard to get examples in Java to read environment variables or parameters from Job definitions. Are there any samples from AWS github.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
