### ISSUE TITLE
Update vCPU and memory guidance for AWS Fargate

### ISSUE THREAD

**Issue by stevenfollis** [awsdocs/aws-batch-user-guide#30]
The [AWS Batch on AWS Fargate](https://docs.aws.amazon.com/batch/latest/userguide/fargate.html#when-to-use-fargate) page currently states that: 

> However, we recommend that you use Amazon EC2 if your jobs require any of the following:
  More than four vCPUs
  More than 30 gibibytes (GiB) of memory

However this was [updated in Oct 2022](https://aws.amazon.com/about-aws/whats-new/2022/10/aws-batch-increases-compute-memory-resource-configurations-fargate-type-jobs-4x/) to have 16 vCPU and 120GiB of memory. 

The document should be updated to reflect this change.

**Comment by HLeeHart** [comment]
Thank you for pointing this out and providing the fix. Docs.aws.amazon.com will be updated later today.
