### ISSUE TITLE
The dependent job only runs when the independent job succeeds. What if I wish to trigger a job when the independent job completes (fail or pass). Do I need to monitor manually 

### ISSUE THREAD

**Issue by wsrfad** [awsdocs/aws-batch-user-guide#32]
May be this is the last stage of a pipeline..Which needs to tell the job has completed..

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
