### ISSUE TITLE
Help Wanted - Example Job Definitions

### ISSUE THREAD

**Issue by nrdlngr** [awsdocs/aws-batch-user-guide#9]
Please share your example job definitions! If you have a useful or interesting job definition example that you feel other users could benefit from, let us know.

Submit a pull request (instructions [here](https://github.com/awsdocs/aws-batch-user-guide/blob/master/CONTRIBUTING.md)) or send me a note via the Comments below. If your suggestion is likely to help others, I'll add it to the list of example job definitions [here](https://docs.aws.amazon.com/batch/latest/userguide/example-job-definitions.html) in the AWS Batch User Guide.

Thank you for your time. We look forward to hearing from you!

**Comment by Grigor88451201** [comment]
G

**Comment by HLeeHart** [comment]
Closing this old issue - it's served it's purpose, and we're now to keep our issue count low by addressing the issues.
